export const CartTypesAction = {
    ADD_ACTION: 'ADD_ACTION',
    CART_HIDDENT_ACTION: 'CART_HIDDEN_ACTION',
    REMOVE_CART_ACTION: 'REMOVE_CART_ACTION',
    INCREASE_CART_ACTION: 'INCREASE_CART_ACTION',
    DECREASE_CART_ACTION: 'DECREASE_CART_ACTION'
}